name: CI/CD Pipeline NodeSimpleApp

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test || echo "Sin pruebas definidas"

      - name: Desplegar aplicación al servidor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy/nodesimpleapp
            git pull origin main
            npm install
            pm2 restart all
